#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dwarves
Version  : 1.24
Release  : 12
URL      : https://git.kernel.org/pub/scm/devel/pahole/pahole.git/snapshot/pahole-1.24.tar.gz
Source0  : https://git.kernel.org/pub/scm/devel/pahole/pahole.git/snapshot/pahole-1.24.tar.gz
Source1  : https://github.com/libbpf/libbpf/archive/v1.0.0/libbpf-1.0.0.tar.gz
Summary  : Debugging Information Manipulation Tools (pahole & friends)
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: dwarves-bin = %{version}-%{release}
Requires: dwarves-data = %{version}-%{release}
Requires: dwarves-lib = %{version}-%{release}
Requires: dwarves-license = %{version}-%{release}
Requires: dwarves-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : pkg-config
BuildRequires : pkgconfig(libbpf)
BuildRequires : pkgconfig(libdw)
BuildRequires : python3-dev
BuildRequires : zlib-dev

%description
dwarves is a set of tools that use the debugging information inserted in
ELF binaries by compilers such as GCC, used by well known debuggers such as
GDB, and more recent ones such as systemtap.

Utilities in the dwarves suite include pahole, that can be used to find
alignment holes in structs and classes in languages such as C, C++, but not
limited to these.

It also extracts other information such as CPU cacheline alignment, helping
pack those structures to achieve more cache hits.

These tools can also be used to encode and read the BTF type information format
used with the Linux kernel bpf syscall, using 'pahole -J' and 'pahole -F btf'.

A diff like tool, codiff can be used to compare the effects changes in source
code generate on the resulting binaries.

Another tool is pfunct, that can be used to find all sorts of information about
functions, inlines, decisions made by the compiler about inlining, etc.

One example of pfunct usage is in the fullcircle tool, a shell that drivers
pfunct to generate compileable code out of a .o file and then build it using
gcc, with the same compiler flags, and then use codiff to make sure the
original .o file and the new one generated from debug info produces the same
debug info.

Pahole also can be used to use all this type information to pretty print raw data
according to command line directions.

Headers can have its data format described from debugging info and offsets from
it can be used to further format a number of records.

The btfdiff utility compares the output of pahole from BTF and DWARF to make
sure they produce the same results.

%package bin
Summary: bin components for the dwarves package.
Group: Binaries
Requires: dwarves-data = %{version}-%{release}
Requires: dwarves-license = %{version}-%{release}

%description bin
bin components for the dwarves package.


%package data
Summary: data components for the dwarves package.
Group: Data

%description data
data components for the dwarves package.


%package dev
Summary: dev components for the dwarves package.
Group: Development
Requires: dwarves-lib = %{version}-%{release}
Requires: dwarves-bin = %{version}-%{release}
Requires: dwarves-data = %{version}-%{release}
Provides: dwarves-devel = %{version}-%{release}
Requires: dwarves = %{version}-%{release}

%description dev
dev components for the dwarves package.


%package lib
Summary: lib components for the dwarves package.
Group: Libraries
Requires: dwarves-data = %{version}-%{release}
Requires: dwarves-license = %{version}-%{release}

%description lib
lib components for the dwarves package.


%package license
Summary: license components for the dwarves package.
Group: Default

%description license
license components for the dwarves package.


%package man
Summary: man components for the dwarves package.
Group: Default

%description man
man components for the dwarves package.


%prep
%setup -q -n pahole-1.24
cd %{_builddir}
tar xf %{_sourcedir}/libbpf-1.0.0.tar.gz
cd %{_builddir}/pahole-1.24
mkdir -p lib/bpf
cp -r %{_builddir}/libbpf-1.0.0/* %{_builddir}/pahole-1.24/lib/bpf

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1661368633
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake .. -D__LIB=lib
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1661368633
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dwarves
cp %{_builddir}/libbpf-1.0.0/LICENSE.LGPL-2.1 %{buildroot}/usr/share/package-licenses/dwarves/91c66db733cf0ff2b3216ec4223b940daf6b26d4 || :
cp %{_builddir}/pahole-%{version}/COPYING %{buildroot}/usr/share/package-licenses/dwarves/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/btfdiff
/usr/bin/codiff
/usr/bin/ctracer
/usr/bin/dtagnames
/usr/bin/fullcircle
/usr/bin/ostra-cg
/usr/bin/pahole
/usr/bin/pdwtags
/usr/bin/pfunct
/usr/bin/pglobal
/usr/bin/prefcnt
/usr/bin/scncopy
/usr/bin/syscse

%files data
%defattr(-,root,root,-)
/usr/share/dwarves/runtime/Makefile
/usr/share/dwarves/runtime/ctracer_relay.c
/usr/share/dwarves/runtime/ctracer_relay.h
/usr/share/dwarves/runtime/linux.blacklist.cu
/usr/share/dwarves/runtime/python/ostra.py

%files dev
%defattr(-,root,root,-)
/usr/include/dwarves/btf_encoder.h
/usr/include/dwarves/config.h
/usr/include/dwarves/ctf.h
/usr/include/dwarves/dutil.h
/usr/include/dwarves/dwarves.h
/usr/include/dwarves/dwarves_emit.h
/usr/include/dwarves/dwarves_reorganize.h
/usr/include/dwarves/elf_symtab.h
/usr/include/dwarves/elfcreator.h
/usr/include/dwarves/gobuffer.h
/usr/include/dwarves/hash.h
/usr/include/dwarves/libctf.h
/usr/include/dwarves/list.h
/usr/include/dwarves/rbtree.h
/usr/lib64/libdwarves.so
/usr/lib64/libdwarves_emit.so
/usr/lib64/libdwarves_reorganize.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdwarves.so.1
/usr/lib64/libdwarves.so.1.0.0
/usr/lib64/libdwarves_emit.so.1
/usr/lib64/libdwarves_emit.so.1.0.0
/usr/lib64/libdwarves_reorganize.so.1
/usr/lib64/libdwarves_reorganize.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dwarves/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/dwarves/91c66db733cf0ff2b3216ec4223b940daf6b26d4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pahole.1
