#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dwarves
Version  : 1.12
Release  : 1
URL      : https://git.kernel.org/pub/scm/devel/pahole/pahole.git/snapshot/pahole-1.12.tar.gz
Source0  : https://git.kernel.org/pub/scm/devel/pahole/pahole.git/snapshot/pahole-1.12.tar.gz
Summary  : Debugging Information Manipulation Tools
Group    : Development/Tools
License  : GPL-2.0
Requires: dwarves-bin
Requires: dwarves-lib
Requires: dwarves-license
Requires: dwarves-data
Requires: dwarves-man
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(libdw)
BuildRequires : zlib-dev

%description
dwarves is a set of tools that use the debugging information inserted in
ELF binaries by compilers such as GCC, used by well known debuggers such as
GDB, and more recent ones such as systemtap.

Utilities in the dwarves suite include pahole, that can be used to find
alignment holes in structs and classes in languages such as C, C++, but not
limited to these.

It also extracts other information such as CPU cacheline alignment, helping
pack those structures to achieve more cache hits.

These tools can also be used to encode the BTF type information format used with
the Linux kernel bpf syscall, using 'pahole -J'.

A diff like tool, codiff can be used to compare the effects changes in source
code generate on the resulting binaries.

Another tool is pfunct, that can be used to find all sorts of information about
functions, inlines, decisions made by the compiler about inlining, etc.

%package bin
Summary: bin components for the dwarves package.
Group: Binaries
Requires: dwarves-data
Requires: dwarves-license
Requires: dwarves-man

%description bin
bin components for the dwarves package.


%package data
Summary: data components for the dwarves package.
Group: Data

%description data
data components for the dwarves package.


%package dev
Summary: dev components for the dwarves package.
Group: Development
Requires: dwarves-lib
Requires: dwarves-bin
Requires: dwarves-data
Provides: dwarves-devel

%description dev
dev components for the dwarves package.


%package lib
Summary: lib components for the dwarves package.
Group: Libraries
Requires: dwarves-data
Requires: dwarves-license

%description lib
lib components for the dwarves package.


%package license
Summary: license components for the dwarves package.
Group: Default

%description license
license components for the dwarves package.


%package man
Summary: man components for the dwarves package.
Group: Default

%description man
man components for the dwarves package.


%prep
%setup -q -n pahole-1.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534461935
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1534461935
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/dwarves
cp COPYING %{buildroot}/usr/share/doc/dwarves/COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/codiff
/usr/bin/ctracer
/usr/bin/dtagnames
/usr/bin/ostra-cg
/usr/bin/pahole
/usr/bin/pdwtags
/usr/bin/pfunct
/usr/bin/pglobal
/usr/bin/prefcnt
/usr/bin/scncopy
/usr/bin/syscse

%files data
%defattr(-,root,root,-)
/usr/share/dwarves/runtime/Makefile
/usr/share/dwarves/runtime/ctracer_relay.c
/usr/share/dwarves/runtime/ctracer_relay.h
/usr/share/dwarves/runtime/linux.blacklist.cu
/usr/share/dwarves/runtime/python/ostra.py

%files dev
%defattr(-,root,root,-)
/usr/include/dwarves/dutil.h
/usr/include/dwarves/dwarves.h
/usr/include/dwarves/dwarves_emit.h
/usr/include/dwarves/dwarves_reorganize.h
/usr/include/dwarves/gobuffer.h
/usr/include/dwarves/list.h
/usr/include/dwarves/rbtree.h
/usr/include/dwarves/strings.h
/usr/lib64/libdwarves.so
/usr/lib64/libdwarves_emit.so
/usr/lib64/libdwarves_reorganize.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdwarves.so.1
/usr/lib64/libdwarves.so.1.0.0
/usr/lib64/libdwarves_emit.so.1
/usr/lib64/libdwarves_emit.so.1.0.0
/usr/lib64/libdwarves_reorganize.so.1
/usr/lib64/libdwarves_reorganize.so.1.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/dwarves/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/pahole.1
